In [2]:
import numpy as np 

In [4]:
lst = []
with open('D:\\baitapvandungchuong3\\baseball_2D.txt', 'r', encoding='utf-8-sig') as file:
    for i in file:
        data = i.replace('[','').replace(']','').split(',')
np_baseball = np.array(data).astype(int)
np_baseball

array([ 74, 180,  74, ..., 190,  73, 195])

In [8]:
np_baseball= np_baseball.reshape(-1,2)
np_baseball

array([[ 74, 180],
       [ 74, 215],
       [ 72, 210],
       ...,
       [ 75, 205],
       [ 75, 190],
       [ 73, 195]])

In [9]:
# giá trị thứ 50 là
np_baseball[50]


array([ 73, 200])

In [ ]:
# tạo array cân nặng
np_weight = np_baseball[:,0]
np_weight

array([74, 74, 72, ..., 75, 75, 73])

In [13]:
#4
#chiều cao của vận động viên thứ 124
np_baseball[124,1]

np.int64(210)

In [15]:
#5
print("chiều cao trung bình của các cầu thủ là : ", np.mean(np_baseball[:,1]))
print("cân nặng trung bình của các cầu thủ là : ", np.mean(np_baseball[:,0]))

chiều cao trung bình của các cầu thủ là :  201.34876847290641
cân nặng trung bình của các cầu thủ là :  73.6896551724138


In [16]:
#6
# ta thấy chiều cao tỉ lệ thuận với cân nặng
